RootTable:      RootTable.o myLinkedList.o
                gcc RootTable.o myLinkedList.o -o RootTable.exe:

RootTable.o:    RootTable.o myLinkedList.h
                gcc -c RootTable.c:

myLinkedList.o: myLinkedList.c myLinkedList.h
                gcc -c myLinkedList.c: